language: java
jdk:
  - oraclejdk8

install:
  # Install Srclib
  - mkdir -p $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - curl -Lo $HOME/bin/srclib.gz https://srclib-release.s3.amazonaws.com/srclib/0.1.1-no-docker5/linux-amd64/srclib.gz 
  - gunzip -c $HOME/bin/srclib.gz > $HOME/bin/srclib
  - sudo chmod +x $HOME/bin/srclib
  # Build this toolchain
  - make
  - mkdir -p $HOME/.srclib/sourcegraph.com/sourcegraph
  - ln -s $TRAVIS_BUILD_DIR $HOME/.srclib/sourcegraph.com/sourcegraph/srclib-java

script:
# Only make the tests that pass on jdk8. The error tolerance test
# requires a manually installed version of jdk8u, which is a pain on
# Travis.
  - make install
  - srclib test testdata/case/java-gradle-sample testdata/case/java-jdk-sample testdata/case/java-maven-sample
