language: java
jdk:
  - oraclejdk8

install:
# installing srclib
  - mkdir $HOME/gocode
  - export GOPATH=$HOME/gocode
  - go get -u -v sourcegraph.com/sourcegraph/srclib/cmd/srclib
  - export PATH=$PATH:$HOME/gocode/bin
  # Build this toolchain
  - make
  - mkdir -p $HOME/.srclib/sourcegraph.com/sourcegraph
  - ln -s $TRAVIS_BUILD_DIR $HOME/.srclib/sourcegraph.com/sourcegraph/srclib-java

script:
# Only make the tests that pass on jdk8. The error tolerance test
# requires a manually installed version of jdk8u, which is a pain on
# Travis.
  - make install
  - srclib test testdata/case/java-gradle-sample testdata/case/java-jdk-sample testdata/case/java-maven-sample
